Lesson10
ivanprofpv/test-guru pull request #10
Opened 2022-08-02 07:55 UTC by ivanprofpv

У меня вопрос по заданию:
5. Разрешите действия над остальными ресурсами только для пользователя который вошел в систему

Когда смотрел скринкаст, там добавили в ApplicationController метод authenticate_user!, это же и соответствует этой задаче?

2022-08-02 16:51 UTC, BubuntuClu requested changes

2022-08-02 16:51 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +  def cookie_path(path)
где используется этот метод?

2022-08-02 16:51 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +    cookies[:path] = path
ключ `path`не информативный. что это за путь? что в себе хранит?

2022-08-02 16:51 UTC, BubuntuClu commented on app/controllers/sessions_controller.rb
> +      redirect_to cookies[:path] #для редиректа на ту же страницу, откуда заходим
`redirect_to cookies[:понятное_имя_ключа] || root_path`

2022-08-02 16:51 UTC, BubuntuClu commented on app/helpers/sessions_helper.rb
> +  def flash_message(type)
где используется этот метод?

2022-08-02 16:51 UTC, BubuntuClu commented on app/helpers/sessions_helper.rb
> +  def flash_message(type)
если у тебя будет много разных ключей во флэше лежать, то надо будет вызывать этот метод с каждым ключем? умрешь перебирать их все) сделай перебор внутри этого метода

2022-08-02 16:51 UTC, BubuntuClu commented on app/models/user.rb
> +  validates :email, uniqueness: true
`presence` почему заменил? нужно оставить и униклаьность добавить

2022-08-02 16:51 UTC, BubuntuClu commented on app/views/sessions/_form.html.erb
> +  <%= content_tag :p, flash[:alert], class: 'flash alert' %>
где-то подобный код уже был

2022-08-02 16:51 UTC, BubuntuClu commented on config/routes.rb
> +  get 'sessions/new'
дублирует роут на 9ой строке

2022-08-02 16:51 UTC, BubuntuClu commented on config/routes.rb
> +  get 'users/new'
дублирует роут на 8ой строке

2022-08-02 16:51 UTC, BubuntuClu commented on db/migrate/20220731175216_change_table_rename_password_to_users.rb
> +  t.rename :password, :password_digest
отступ

2022-08-02 16:51 UTC, BubuntuClu commented on db/schema.rb
>      t.string "email", null: false
уникальный индекс в БД надо добавить

2022-08-03 06:39 UTC, ivanprofpv commented on app/controllers/sessions_controller.rb
> +      redirect_to cookies[:path] #для редиректа на ту же страницу, откуда заходим
исправил + назвал по другому путь

2022-08-03 06:41 UTC, ivanprofpv commented on app/helpers/sessions_helper.rb
> +  def flash_message(type)
> где используется этот метод?

Забыл добавить во вью /sessions/_form.html.erb

> если у тебя будет много разных ключей во флэше лежать, то надо будет вызывать этот метод с каждым ключем? умрешь перебирать их все) сделай перебор внутри этого метода

через if сделал

2022-08-03 06:42 UTC, ivanprofpv commented on app/models/user.rb
> +  validates :email, uniqueness: true
Случайно. Восстановил, добавил уникальность и добавил доп.валидацию через константу

2022-08-03 06:42 UTC, ivanprofpv commented on config/routes.rb
> +  get 'sessions/new'
дубль убрал

2022-08-03 06:42 UTC, ivanprofpv commented on config/routes.rb
> +  get 'users/new'
Дубль убрал

2022-08-03 06:42 UTC, ivanprofpv commented on db/migrate/20220731175216_change_table_rename_password_to_users.rb
> +  t.rename :password, :password_digest
Добавил

2022-08-03 06:44 UTC, ivanprofpv commented on db/schema.rb
>      t.string "email", null: false
уникальный индекс добавлю вечером через миграцию, исправления вносил через винду, а здесь надо и гемфайл и еще некоторые настройки менять, чтобы миграции работали.

2022-08-03 07:13 UTC, BubuntuClu requested changes

2022-08-03 07:13 UTC, BubuntuClu commented on app/controllers/sessions_controller.rb
> +      redirect_to cookies[:login_url] || root_path #для редиректа на ту же страницу, откуда заходим
не вижу кода, который сохраняет адрес в эту куку. вижу только использование этой куки. и ключ `login_url` тоже плохой. ты ведь туда должен класть адрес куда пользоватлеь хотел зайти. `login_url` об этом не говорит

2022-08-03 07:13 UTC, BubuntuClu commented on app/helpers/sessions_helper.rb
> +    if flash[:alert]
а если во флэше будет другой ключ? тут будет еще один if? сделай перебор положенный ключей в объект флэша

2022-08-04 09:42 UTC, merged