Lesson11
ivanprofpv/test-guru pull request #11
Opened 2022-08-09 05:06 UTC by ivanprofpv

Файлы по задачам из урока 11.

2022-08-09 06:45 UTC, BubuntuClu requested changes

2022-08-09 06:45 UTC, BubuntuClu commented on app/controllers/admin/base_controller.rb
> +    redirect_to root_path, alert: 'You are not authorized ti view this page.' unless current_user.is_a?(Admin)
добавь метод в модель `User` который будет проверять является ли пользователь админом. `current_user.admin?`

2022-08-09 06:45 UTC, BubuntuClu commented on app/controllers/admin/tests_controller.rb
> +  def start
в админке старт не нужен

2022-08-09 06:45 UTC, BubuntuClu commented on app/controllers/admin/tests_controller.rb
> +    @test = Test.create(test_params)
нужно назначать автора теста

2022-08-09 06:45 UTC, BubuntuClu commented on db/seeds.rb
> +ruby_test = Test.create(title: 'Ruby', level: 3)
это ведь все не будет работать. у тебя нет привязок объектов к родитесльким сущностям

2022-08-09 07:14 UTC, ivanprofpv commented on app/controllers/admin/base_controller.rb
> +    redirect_to root_path, alert: 'You are not authorized ti view this page.' unless current_user.is_a?(Admin)
Добавил

2022-08-09 07:14 UTC, ivanprofpv commented on app/controllers/admin/tests_controller.rb
> +  def start
Убрал

2022-08-09 07:15 UTC, ivanprofpv commented on app/controllers/admin/tests_controller.rb
> +    @test = Test.create(test_params)
Назначил

2022-08-10 16:38 UTC, BubuntuClu requested changes

2022-08-10 16:38 UTC, BubuntuClu commented on db/seeds.rb
> +ruby_test = backend.tests.create!(title: 'Ruby', level: 3, author_id: 1)
а откуда зардкод id взался? в телеграме вроде обсудили что его не должно быть. хоть мы и обсуждали вопросы, но это не позволяет делать это в других местах

2022-08-10 16:38 UTC, BubuntuClu commented on db/seeds.rb
> +                {body: 'Yes', question_id: 1, correct: true},
1 - слушай, а тут `question_id` уже ведь и не нужен вовсе. ты ведь через ассоциацию создаешь
2 - даже если указываешь этот параметр, он должен определяться не через хардкод, а динамически

2022-08-10 16:38 UTC, BubuntuClu commented on app/controllers/sessions_controller.rb
> +    @user = User.find_by(email: params[:email])
почему тут добавилась собачка?

2022-08-14 18:41 UTC, closed without merging