Lesson18
ivanprofpv/test-guru pull request #18
Opened 2022-10-03 12:39 UTC by ivanprofpv

2022-10-03 17:38 UTC, BubuntuClu requested changes

2022-10-03 17:38 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +  def how_much_time_left?
может это вынести в модель пассажа?

2022-10-03 17:38 UTC, BubuntuClu commented on app/javascript/packs/timer.js
> +      } else
тут нет опечатки? `else` тут нужен?

2022-10-03 17:38 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  def create_timer
какое-то странное название метода. оно соответсвует тому что возвращается в результате?

2022-10-03 17:38 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    @current_test.test_passages.where(user: @current_user, passed: true).count == 1
если ты отлфильтруешь  `passed: true` так, то у тебя условие не будет работать правильно. ты можешь 100 раз завалить тест и пройти один раз успешно, то получишь бадж.

2022-10-03 17:38 UTC, BubuntuClu commented on app/services/badge_service.rb
> +  def level_rule_completed(badge)
а нужно сюда бадж передавать? может сразу значение?

2022-10-04 05:10 UTC, ivanprofpv commented on app/javascript/packs/timer.js
> +      } else
собирался по другому сделать, не удалил видимо, а ошибки не было.

2022-10-04 05:10 UTC, ivanprofpv commented on app/controllers/test_passages_controller.rb
> +  def how_much_time_left?
Перенес в модель

2022-10-04 09:10 UTC, ivanprofpv commented on app/models/test_passage.rb
> +  def create_timer
переименовал в get_timer. То не совсем корректное конечно

2022-10-04 17:49 UTC, ivanprofpv commented on app/services/badge_service.rb
> +  def level_rule_completed(badge)
упростил

2022-10-04 17:51 UTC, ivanprofpv commented on app/services/badge_service.rb
> +    @current_test.test_passages.where(user: @current_user, passed: true).count == 1
что то пока не могу придумать решение. Приходит на ум сделать проверку пройден тест или нет успешно, но опять же это не решит проблему "пройдено с первого раза".

2022-10-05 07:13 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    tests.joins(:test_passages)
тебе нужно посчитать количество прохождений этого теста каким-то пользователем и у знать текущее прохождение было успешное или нет.
фильтрации по `passed` не нужно делать

2022-10-06 04:05 UTC, closed without merging