Lesson18.1 timer
ivanprofpv/test-guru pull request #19
Opened 2022-10-05 11:03 UTC by ivanprofpv

2022-10-05 16:43 UTC, BubuntuClu requested changes

2022-10-05 16:43 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    completed = @current_user.test_passages
это лишний запрос. зачем он тут?
тебе надо:
1 - посчитать количество прохождений тестов пользователем. это ты делаешь на 36ой строке.
2 - проверить что текущее прохождение успешное. как это можно сделать? что у тебя отвечает за текущее прохождение?

2022-10-05 16:43 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    @current_user.tests.where("test_passages.passed = true")
замени строку `"test_passages.passed = true"` на `AR` синтаксис. через символы

2022-10-06 04:18 UTC, ivanprofpv commented on app/services/badge_service.rb
> +    completed = @current_user.test_passages
2 - passed = true

2022-10-06 04:25 UTC, ivanprofpv commented on app/services/badge_service.rb
> +    completed = @current_user.test_passages
либо модель test_passages, если это имеется в виду

2022-10-06 04:40 UTC, closed without merging