Файлы после выполнения задач из 6 урока
ivanprofpv/test-guru pull request #6
Opened 2022-07-11 17:23 UTC by ivanprofpv

2022-07-12 07:04 UTC, BubuntuClu requested changes

2022-07-12 07:04 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :search_tests_category, ->(category) {
сортировку и выборку не надо помещать в скоуп.
скоуп должен возвращать объект ActiveRecord::Relation, pluck возвращает массив.
так же скоуп это универсальный метод, который может использован в разных частях приложения, там может потребоваться другая сортировка и выборка.
метод надо оставить, заменить часть выражения на скоуп и уже к скоупу применить сортировку и выборку

2022-07-12 07:04 UTC, BubuntuClu commented on app/models/test.rb
> +  validates :title, uniqueness: true
1 - валидации можно записывать в одну `validates`, перечисляя опции через `,`
2 - уникальными должны быть пары значеие `title+level`, а не каждый сам по себе
3 - ограничения надо дублировать на всех уровнях приложения. можно через СУБД насоздавать данных, которые для приложения не будут валидны. в БД добавить уникальный составной индекс надо

2022-07-12 07:04 UTC, BubuntuClu commented on app/models/user.rb
> +  #перенес в test.rb в виде scope
покажи вызов этого скоупа. результат равносилен ли коду, что был тут раньше?

2022-07-12 07:04 UTC, BubuntuClu commented on db/schema.rb
> +    t.string "body", null: false
где миграции, которые меняют эти поля?
`t.string "body", null: false`
`t.string "email", null: false`
ты у себя локально сменил, а как быть тем кто подтянет твой код?

2022-07-13 06:11 UTC, BubuntuClu commented on app/models/test.rb
> +  validates :title, presence: true
`validates :title, presence: true, uniqueness: { scope: :level }`

2022-07-13 06:23 UTC, ivanprofpv commented on app/models/test.rb
> +  validates :title, presence: true
Ок, учту на будущее

2022-07-15 18:14 UTC, merged