Lesson9.1
ivanprofpv/test-guru pull request #9
Opened 2022-07-28 04:36 UTC by ivanprofpv

2022-07-28 07:19 UTC, BubuntuClu requested changes

2022-07-28 07:19 UTC, BubuntuClu commented on app/controllers/answers_controller.rb
> +    @answer = Answer.new(answer_params)
создавай ответ через ассоциацию вопроса. у тебя в параметрах answer_params нет ключа для вопроса, так что ответ не будет создан никогда

2022-07-28 07:19 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    percentage_correct_answers >= 85
магические числа надо выносить в константу и называть их понятно

2022-07-28 07:19 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    self.current_question = before_update_next_question
это должно делаться через колбэк, а не через вызов метода

2022-07-28 07:19 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  before_validation :before_validation_set_first_question, on: :create
объедини колбэки по выставлению первого и след вопроса в один. внутри метода решай какой нужно выставить вопрос

2022-07-28 07:19 UTC, BubuntuClu commented on db/migrate/20220726111609_drop_table_tests_passeds.rb
> +  def up
если есть метод `up`, то должен быть и метод `down`, чтобы при откатывании миграции не словить ошибку.
в данном случае, метод `down` можно оставить пустым

2022-07-28 10:34 UTC, ivanprofpv commented on app/controllers/answers_controller.rb
> +    @answer = Answer.new(answer_params)
Переделал на создание через ассоциацию question

2022-07-28 10:34 UTC, ivanprofpv commented on app/models/test_passage.rb
> +    percentage_correct_answers >= 85
Вынес в константу. По моему мнению назвал понятно

2022-07-28 10:35 UTC, ivanprofpv commented on app/models/test_passage.rb
> +    self.current_question = before_update_next_question
Перенес в колбэк

2022-07-28 10:36 UTC, ivanprofpv commented on app/models/test_passage.rb
> +  before_validation :before_validation_set_first_question, on: :create
Если правильно понял задачу из этого коммента, то объединил

2022-07-28 10:36 UTC, ivanprofpv commented on db/migrate/20220726111609_drop_table_tests_passeds.rb
> +  def up
По скринкасту автор добавил только up, а down сказал не надо. Добавил и down

2022-07-28 17:45 UTC, BubuntuClu commented on db/migrate/20220726111609_drop_table_tests_passeds.rb
> +  def up
тут у нас с ним расходятся мнения. мне кажется, что миграции должны быть обратимыми, в максимальном количестве случаев

2022-07-28 17:45 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  before_validation :before_validation_set_first_question, on: :create
неа. у тебя все еще два метода before_update_next_question и before_validation_set_first_question.

я говорил про сделать один метод `before_validation_set_question` и внутри него определять нужно поставить первый вопрос или следующий

2022-07-29 05:43 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  before_validation :before_validation_set_question, on: :create
нужно убрать `on: :create` если этот метод должен вызываться не только для создания. либо добавить еще `:update` в список

2022-07-29 05:43 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    self.current_question = if test.present?
у тебя всегда будет ставиться первый вопрос, так как у тебя всегда существует тест. 
неправильно объединил логику методов.

вообще эта история с объединением методов не обязательна, просто круто если сможешь объединить

2022-07-31 17:32 UTC, merged